export const STORY_LIST_REQUEST = "STORY_LIST_REQUEST";
export const STORY_LIST_SUCCESS = "STORY_LIST_SUCCESS";
export const STORY_LIST_ERROR = "STORY_LIST_ERROR";

export const STORY_DETAIL_REQUEST = "STORY_DETAIL_REQUEST";
export const STORY_DETAIL_SUCCESS = "STORY_DETAIL_SUCCESS";
export const STORY_DETAIL_ERROR = "STORY_DETAIL_ERROR";
export const STORY_DETAIL_RESET = "STORY_DETAIL_RESET";

export const STORY_AUTHOR_LIST_REQUEST = "STORY_AUTHOR_LIST_REQUEST";
export const STORY_AUTHOR_LIST_SUCCESS = "STORY_AUTHOR_LIST_SUCCESS";
export const STORY_AUTHOR_LIST_ERROR = "STORY_AUTHOR_LIST_ERROR";

export const STORY_MYSTORIES_LIST_REQUEST = "STORY_MYSTORIES_LIST_REQUEST";
export const STORY_MYSTORIES_LIST_SUCCESS = "STORY_MYSTORIES_LIST_SUCCESS";
export const STORY_MYSTORIES_LIST_ERROR = "STORY_MYSTORIES_LIST_ERROR";



export const STORY_CREATE_REQUEST = "STORY_CREATE_REQUEST";
export const STORY_CREATE_SUCCESS = "STORY_CREATE_SUCCESS";
export const STORY_CREATE_ERROR = "STORY_CREATE_ERROR";
export const STORY_CREATE_RESET = "STORY_CREATE_RESET";

export const STORY_DELETE_REQUEST = "STORY_DELETE_REQUEST";
export const STORY_DELETE_SUCCESS = "STORY_DELETE_SUCCESS";
export const STORY_DELETE_ERROR = "STORY_DELETE_ERROR";
export const STORY_DELETE_RESET = "STORY_DELETE_RESET";

export const STORY_UPDATE_REQUEST = "STORY_UPDATE_REQUEST";
export const STORY_UPDATE_SUCCESS = "STORY_UPDATE_SUCCESS";
export const STORY_UPDATE_ERROR = "STORY_UPDATE_ERROR";
export const STORY_UPDATE_RESET = "STORY_EDIT_RESET";

// 2 ways to request data to server
// a. request separately stories and info
// b. request a single object which contains both info and request

// in my personal opinion requesting seperately would be more useful
