export const AUTHOR_INFO_REQUEST = "AUTHOR_INFO_REQUEST";
export const AUTHOR_INFO_SUCCESS = "AUTHOR_INFO_SUCCESS";
export const AUTHOR_INFO_ERROR = "AUTHOR_INFO_ERROR";
export const AUTHOR_INFO_RESET = "AUTHOR_INFO_RESET";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const AUTHOR_UPDATE_PROFILE_REQUEST = "AUTHOR_UPDATE_PROFILE_REQUEST";
export const AUTHOR_UPDATE_PROFILE_SUCCESS = "AUTHOR_UPDATE_PROFILE_SUCCESS";
export const AUTHOR_UPDATE_PROFILE_FAIL = "AUTHOR_UPDATE_PROFILE_FAIL";

export const AUTHOR_UPDATE_PROFILE_RESET = "AUTHOR_UPDATE_PROFILE_RESET";

export const AUTHOR_LIST_REQUEST = "AUTHOR_LIST_REQUEST";
export const AUTHOR_LIST_SUCCESS = "AUTHOR_LIST_SUCCESS";
export const AUTHOR_LIST_FAIL = "AUTHOR_LIST_FAIL";
